!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitproblem(f2pysetupfunc)
      use problem, only : jmat
      use problem, only : num_tempscales
      use problem, only : num_spin
      use problem, only : nms
      use problem, only : tempscales
      use problem, only : init_problem
      use problem, only : loadexample
      use problem, only : get_cost
      use problem, only : propose
      use problem, only : accept
      use problem, only : get_random_config
      external f2pysetupfunc
      call f2pysetupfunc(jmat,num_tempscales,num_spin,nms,tempscales,ini&
     &t_problem,loadexample,get_cost,propose,accept,get_random_config)
      end subroutine f2pyinitproblem


